import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import HomeCarousel from '@/components/organisms/HomeCarousel'
import Products from '@/components/organisms/Products';
import Comments from '@/components/organisms/Comments'
import 'bootstrap/dist/css/bootstrap.min.css';
import Footer from '../components/molecules/Footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
    <Head>
        <title>freshness</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="./images/freshness.jpg" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@200&display=swap" rel="stylesheet"/>
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
      </Head>
      <header>
  
     </header>
      <main >

      </main>
      <section>
        <HomeCarousel/>
      </section>
      <section>
        <Products/>
              
      </section>
      <section>
        <Comments/>
      </section>

      <footer>
        <Footer/>
      </footer>
    </>
  )
}
